spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: short-url-service
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    serialization:
      write_dates_as_timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  lifecycle:
    timeout-per-shutdown-phase: 20s

logging:
  level:
    root: info
    org:
      springframework:
        web: info

server:
  shutdown: graceful
